// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnzc4kWhTvVIfOrVkE5naDLOdbluCbh1o',
    appId: '1:741521210616:web:d7d28d6a4b8c49f5f60f0d',
    messagingSenderId: '741521210616',
    projectId: 'news-app-e986c',
    authDomain: 'news-app-e986c.firebaseapp.com',
    storageBucket: 'news-app-e986c.firebasestorage.app',
    measurementId: 'G-QLNVQV5PHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnonemRcJ0_uM9Po8ad9hjy1Qt6yFrQ0',
    appId: '1:741521210616:android:521486a86d355d97f60f0d',
    messagingSenderId: '741521210616',
    projectId: 'news-app-e986c',
    storageBucket: 'news-app-e986c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXSJfvykH4gQEdjHEhuYGIspRnrznfxY',
    appId: '1:741521210616:ios:a2ca18ed40d6d4bdf60f0d',
    messagingSenderId: '741521210616',
    projectId: 'news-app-e986c',
    storageBucket: 'news-app-e986c.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXSJfvykH4gQEdjHEhuYGIspRnrznfxY',
    appId: '1:741521210616:ios:a2ca18ed40d6d4bdf60f0d',
    messagingSenderId: '741521210616',
    projectId: 'news-app-e986c',
    storageBucket: 'news-app-e986c.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnzc4kWhTvVIfOrVkE5naDLOdbluCbh1o',
    appId: '1:741521210616:web:96de7e208d1d1cfcf60f0d',
    messagingSenderId: '741521210616',
    projectId: 'news-app-e986c',
    authDomain: 'news-app-e986c.firebaseapp.com',
    storageBucket: 'news-app-e986c.firebasestorage.app',
    measurementId: 'G-B6MVPR8HFC',
  );

}